apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  labels:
    app: cpu-stress
spec:
  containers:
  - name: stress
    image: polinux/stress
    args:
    - "--cpu"
    - "2"
    - "--timeout"
    - "600s"
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"